### ISSUE TITLE
Moving onto the Second Guess

### ISSUE THREAD

**Issue by Lauren-lee1** [ryanlau/apcs#1]
After I submit a correct guess, the game does not move onto the next clue and there is no way for me to finish the game before the timer is up. Not sure how to fix this since my trio was also working on a similar thing.

**Comment by ryanlau** [comment]
To move onto the next clue for a correct guess, in `processGuess` of CelebrityGame, you would remove the celebrity from `_celebGameList` if the guess was right and then set the `_gameCelebrity` to the first element of the `_celebGameList` if there are any celebrities left. 

I'm not sure what you mean by finishing the game before the timer is up.

**Comment by Lauren-lee1** [comment]
When I get the correct guess, it doesn't move onto the next clue. The only way for me to finish the game is when the timer is up

**Comment by ryanlau** [comment]
With the changes mentioned above, correctly guessing the celebrity will move onto to the next celebrity. I just committed with the change.
